version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
    ports:
      # KHÔNG CÒN XUNG ĐỘT: Host Port 8082 tránh 8080 của Jenkins
      - "8082:3000"
    environment:
      # Frontend gọi Backend qua tên dịch vụ 'backend' và cổng nội bộ 8080
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
    ports:
      # HOST Port 3001
      - "3001:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/pet-store
      - JWT_SECRET=a-secret-key-for-jwt
      - CLOUDINARY_CLOUD_NAME=your-cloud-name
      - CLOUDINARY_API_KEY=your-api-key
      - CLOUDINARY_API_SECRET=your-api-secret
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
