version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
    ports:
      # HOST:8082 -> CONTAINER:3000 (Host Port 8082 để tránh xung đột với Jenkins)
      - "8082:3000"
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      # Frontend gọi Backend qua tên dịch vụ 'backend' và cổng nội bộ 8080
      - NEXT_PUBLIC_API_URL=http://backend:8080/api
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end
    ports:
      # HOST:3001 -> CONTAINER:8080
      - "3001:8080"
    volumes:
      - ./back-end:/app
      - /app/node_modules
    environment:
      # Container Backend vẫn chạy trên Port 8080 nội bộ
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/pet-store
      - JWT_SECRET=a-secret-key-for-jwt
      - CLOUDINARY_CLOUD_NAME=your-cloud-name
      - CLOUDINARY_API_KEY=your-api-key
      - CLOUDINARY_API_SECRET=your-api-secret
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

